name: virtual_shop
description: A new Flutter project.



publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'







dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mocktail: ^0.3.0
  mockito: ^5.3.2
  dartz: ^0.10.1
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.2.0
  firebase_core: ^2.4.0
  dio: ^4.0.6
  flutter_modular: ^5.0.3
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  flutter_staggered_grid_view: ^0.6.2
  staggered_grid_view_flutter: ^0.0.4
  transparent_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
